# fly.toml file generated for dnd-server on 2023-04-16T18:14:37+03:00

app = "dnd-server"
primary_region = "otp"

[http_service]
  internal_port = 8080
  force_https = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
